# Email Spam Detection

## Step 1 — Import Libraries and Dataset

In this step, we load the dataset and inspect its basic structure.

In [9]:
import pandas as pd

df = pd.read_csv('/home/ahmed/.cache/kagglehub/datasets/jackksoncsie/spam-email-dataset/versions/1/emails.csv')

df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [11]:
import pandas as pd

df = pd.read_csv('/home/ahmed/.cache/kagglehub/datasets/jackksoncsie/spam-email-dataset/versions/1/emails.csv')

df.columns

Index(['text', 'spam'], dtype='str')

In [12]:
df.shape

(5728, 2)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5728 non-null   str
 1   spam    5728 non-null   int64
dtypes: int64(1), str(1)
memory usage: 89.6 KB

In [18]:
df.describe()

              spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [19]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64